### ISSUE TITLE
3090-24G多卡推理GLM-4V显存问题

### ISSUE THREAD

**Issue by caojialun** [THUDM/GLM-4#103]
### System Info / 系統信息

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 
CUDA_VISIBLE_DEVICES="4,5,6,7,8"
指定多卡，但最终无法运行

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

CUDA_VISIBLE_DEVICES="4,5,6,7,8" python -u "/home/modelscope/glm4/test.py"
使用的modelscope的模版

### Expected behavior / 期待表现

期待回答

**Comment by mxzgn** [comment]
同样多卡也是出现内存不足

**Comment by caojialun** [comment]
我找到解决办法了，根据这个教程安装swift——“https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/glm4v%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md”，再修改下载的模型文件中modeling_chatglm.py中867行，将images_features[i]修改为images_features[i].to(inputs_embeds.device)，最后修改CUDA_VISIBLE_DEVICES应该就好了。

**Comment by slee1023** [comment]
我两张3090-24G，用了zRzRzRzRzRzRzR于6月8日在魔塔更新的generation_config.json和modeling_chatglm.py，跑GLM-4v-9b的OOM问题依旧：设置了device_map="balanced"，看加载过程中，cuda0加载到十多GB停下来，cuda1再加载到十多GB停下来，然后cuda0又继续加载到24GB就爆了，最后都报torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB.

**Comment by zRzRzRzRzRzRzR** [comment]
设置auto呢？我现在跑是一个10 G 一个16G

**Comment by slee1023** [comment]
> 设置auto呢？我现在跑是一个10 G 一个16G

设置auto跟balanced一样，没有区别。

**Comment by slee1023** [comment]
补充：chat的modeling_chatglm.py在5号更新以后，chat是可以正常由双卡加载的。
