### ISSUE TITLE
微调后inferenc.py报错：./aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `probability tensor contains either `inf`, `nan` or element < 0` failed.

### ISSUE THREAD

**Issue by cssaudrey** [THUDM/GLM-4#637]
### System Info / 系統信息

ubutu 22.04
cuda 12.7
python 3.12.7
pytorch 2.5.0
transformers 4.44.0

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

复现：
1 lora 微调
2 运行如下命令： python inference.py  /home/olivia/llm/glm/GLM-4/finetune_demo/output1/checkpoint-1000

报错如下：
(glm-4-demo) olivia@DS-GPU03:~/llm/glm/GLM-4/finetune_demo$ python inference.py  /home/olivia/llm/glm/GLM-4/finetune_demo/output1/checkpoint-1000
Loading checkpoint shards:  30%|█████████████████████████████████▌                                                                              | 3/10 [00:01<00:03,  2.12it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.16it/s]
../aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `probability tensor contains either `inf`, `nan` or element < 0` failed.
╭───────────────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────────────╮
│ /home/olivia/llm/glm/GLM-4/finetune_demo/inference.py:140 in main                                                                                                           │
│                                                                                                                                                                             │
│   137 │   │   "repetition_penalty": 1.2,                                                                                                                                    │
│   138 │   │   "eos_token_id": model.config.eos_token_id,                                                                                                                    │
│   139 │   }                                                                                                                                                                 │
│ ❱ 140 │   outputs = model.generate(**inputs, **generate_kwargs)                                                                                                             │
│   141 │   response = tokenizer.decode(outputs[0][len(inputs['input_ids'][0]):], skip_special_t                                                                              │
│   142 │   print("=========")                                                                                                                                                │
│   143 │   print(response)                                                                                                                                                   │
│                                                                                                                                                                             │
│ /home/olivia/miniconda3/envs/glm-4-demo/lib/python3.12/site-packages/peft/peft_model.py:1704 in generate                                                                    │
│                                                                                                                                                                             │
│   1701 │   │   │   if not peft_config.is_prompt_learning:                                                                                                                   │
│   1702 │   │   │   │   with self._enable_peft_forward_hooks(*args, **kwargs):                                                                                               │
│   1703 │   │   │   │   │   kwargs = {k: v for k, v in kwargs.items() if k not in self.special_p                                                                             │
│ ❱ 1704 │   │   │   │   │   outputs = self.base_model.generate(*args, **kwargs)                                                                                              │
│   1705 │   │   │   else:                                                                                                                                                    │
│   1706 │   │   │   │   outputs = self.base_model.generate(**kwargs)                                                                                                         │
│   1707 │   │   except:                                                                                                                                                      │
│                                                                                                                                                                             │
│ /home/olivia/miniconda3/envs/glm-4-demo/lib/python3.12/site-packages/torch/utils/_contextlib.py:116 in decorate_context                                                     │
│                                                                                                                                                                             │
│   113 │   @functools.wraps(func)                                                                                                                                            │
│   114 │   def decorate_context(*args, **kwargs):                                                                                                                            │
│   115 │   │   with ctx_factory():                                                                                                                                           │
│ ❱ 116 │   │   │   return func(*args, **kwargs)                                                                                                                              │
│   117 │                                                                                                                                                                     │
│   118 │   return decorate_context                                                                                                                                           │
│   119                                                                                                                                                                       │
│                                                                                                                                                                             │
│ /home/olivia/miniconda3/envs/glm-4-demo/lib/python3.12/site-packages/transformers/generation/utils.py:2024 in generate                                                      │
│                                                                                                                                                                             │
│   2021 │   │   │   )                                                                                                                                                        │
│   2022 │   │   │                                                                                                                                                            │
│   2023 │   │   │   # 13. run sample (it degenerates to greedy search when `generation_config.do                                                                             │
│ ❱ 2024 │   │   │   result = self._sample(                                                                                                                                   │
│   2025 │   │   │   │   input_ids,                                                                                                                                           │
│   2026 │   │   │   │   logits_processor=prepared_logits_processor,                                                                                                          │
│   2027 │   │   │   │   logits_warper=prepared_logits_warper,                                                                                                                │
│                                                                                                                                                                             │
│ /home/olivia/miniconda3/envs/glm-4-demo/lib/python3.12/site-packages/transformers/generation/utils.py:3020 in _sample                                                       │
│                                                                                                                                                                             │
│   3017 │   │   │   if do_sample:                                                                                                                                            │
│   3018 │   │   │   │   probs = nn.functional.softmax(next_token_scores, dim=-1)                                                                                             │
│   3019 │   │   │   │   # TODO (joao): this OP throws "skipping cudagraphs due to ['incompatible                                                                             │
│ ❱ 3020 │   │   │   │   next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)                                                                                     │
│   3021 │   │   │   else:                                                                                                                                                    │
│   3022 │   │   │   │   next_tokens = torch.argmax(next_token_scores, dim=-1)                                                                                                │
│   3023                                                                                                                                                                      │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Expected behavior / 期待表现

推理成功

**Comment by zRzRzRzRzRzRzR** [comment]
看上去是词表的问题，你使用BF16微调和推理的吗

**Comment by cssaudrey** [comment]
谢谢回复。我用的这里的样例代码，基于源码的lora.yaml 做的微调，是使用的BF16.
我使用自己的训练数据，会不会是训练数据有问题?
我的训练数据只有90条，一个data set 同时做了train_data，test_data, eval_data

**Comment by Andy1018** [comment]
@cssaudrey @zRzRzRzRzRzRzR 请问问题解决了吗，我用LLaMA-Factory lora方式微调后，同样的错误

**Comment by cssaudrey** [comment]
还是没有跑通。我注释了**do_sample**，有输出，但是输出全部是“！！！！！！！！”。 @zRzRzRzRzRzRzR  麻烦提一点提示。

见如下：
(glm-4-demo) olivia@DS-GPU03:~/llm/glm/GLM-4/finetune_demo$ python inference.py  /home/olivia/llm/glm/GLM-4/finetune_demo/output/checkpoint-1000
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.99it/s]
/home/olivia/miniconda3/envs/glm-4-demo/lib/python3.12/site-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
========= output =========
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Andy1018** [comment]
(glm4) [root@adsl-172-10-0-187 basic_demo]# python openai_api_request.py 
ChatCompletion(id='chatcmpl-ZPaE1pu1lJo7XBetF5gIRHYH7LKBK', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!', refusal=None, role='assistant', audio=None, function_call=None, tool_calls=None))], created=1731026510, model='glm-4', object='chat.completion', service_tier=None, system_fingerprint='fp_xJsllLODf', usage=CompletionUsage(completion_tokens=256, prompt_tokens=47, total_tokens=303, completion_tokens_details=None, prompt_tokens_details=None))

**Comment by sixsixcoder** [comment]
我在pytorch2.4.0和transformers4.45.0按照您的步骤可以正常运行微调后的推理

**Comment by Andy1018** [comment]
> 我在pytorch2.4.0和transformers4.45.0按照您的步骤可以正常运行微调后的推理

用的是llama-factory微调的？

**Comment by Andy1018** [comment]
@sixsixcoder 确实可以了，感谢支持！

**Comment by cssaudrey** [comment]
确实可以了 @sixsixcoder  谢谢支持！
