### ISSUE TITLE
GLM4官方代码VLLM启动的时候报异常。

### ISSUE THREAD

**Issue by starage2020** [THUDM/GLM-4#677]
GLM4官方代码，执行的时候报了异常
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, trust_remote_code=True)
    engine_args = AsyncEngineArgs(
        model=MODEL_PATH,
        tokenizer=MODEL_PATH,
        # 如果你有多张显卡，可以在这里设置成你的显卡数量
        tensor_parallel_size=1,
        dtype="float16",
        trust_remote_code=True,
        gpu_memory_utilization=0.98,
        enforce_eager=True,
        worker_use_ray=False,
        engine_use_ray=False,
        disable_log_requests=True,
        max_model_len=MAX_MODEL_LENGTH,
    )
    engine = AsyncLLMEngine.from_engine_args(engine_args)
以前代码运行一直正常，最近突然失败，，错误信息如下：
Special tokens have been added in the vocabulary, make sure the associated word                                                                                                                                                                                                                                              embeddings are fine-tuned or trained.
WARNING 12-19 08:15:06 config.py:1155] Casting torch.bfloat16 to torch.float16.
INFO 12-19 08:15:06 llm_engine.py:161] Initializing an LLM engine (v0.4.3) with                                                                                                                                                                                                                                              config: model='/app/glm-4-9b-chat', speculative_config=None, tokenizer='/app/glm                                                                                                                                                                                                                                             -4-9b-chat', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope                                                                                                                                                                                                                                             _scaling=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.floa                                                                                                                                                                                                                                             t16, max_seq_len=65536, download_dir=None, load_format=LoadFormat.AUTO, tensor_p                                                                                                                                                                                                                                             arallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eage                                                                                                                                                                                                                                             r=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, d                                                                                                                                                                                                                                             ecoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, serve                                                                                                                                                                                                                                             d_model_name=/app/glm-4-9b-chat)
Special tokens have been added in the vocabulary, make sure the associated word                                                                                                                                                                                                                                              embeddings are fine-tuned or trained.
WARNING 12-19 08:15:06 tokenizer.py:126] Using a slow tokenizer. This might caus                                                                                                                                                                                                                                             e a significant slowdown. Consider using a fast tokenizer instead.
/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:619: UserWarning:                                                                                                                                                                                                                                              Can't initialize NVML
  warnings.warn("Can't initialize NVML")
INFO 12-19 08:15:07 selector.py:120] Cannot use FlashAttention-2 backend for Vol                                                                                                                                                                                                                                             ta and Turing GPUs.
INFO 12-19 08:15:07 selector.py:51] Using XFormers backend.
[E socket.cpp:957] [c10d] The client socket has timed out after 600s while tryin                                                                                                                                                                                                                                             g to connect to (10.64.1.1, 53591).
Traceback (most recent call last):
  File "/app/basic_demo/openai_api_server.py", line 694, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py"                                                                                                                                                                                                                                             , line 386, in from_engine_args
    engine = cls(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py"                                                                                                                                                                                                                                             , line 340, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py"                                                                                                                                                                                                                                             , line 462, in _init_engine
    return engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line                                                                                                                                                                                                                                              222, in __init__
    self.model_executor = executor_class(
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py",                                                                                                                                                                                                                                              line 41, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py",                                                                                                                                                                                                                                              line 23, in _init_executor
    self.driver_worker.init_device()
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 114                                                                                                                                                                                                                                             , in init_device
    init_worker_distributed_environment(self.parallel_config, self.rank,
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 346                                                                                                                                                                                                                                             , in init_worker_distributed_environment
    init_distributed_environment(parallel_config.world_size, rank,
  File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.                                                                                                                                                                                                                                             py", line 96, in init_distributed_environment
    torch.distributed.init_process_group(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py                                                                                                                                                                                                                                             ", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py                                                                                                                                                                                                                                             ", line 89, in wrapper
    func_return = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c1                                                                                                                                                                                                                                             0d.py", line 1305, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/rendezvous.py"                                                                                                                                                                                                                                             , line 199, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, t                                                                                                                                                                                                                                             imeout, use_libuv)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/rendezvous.py"                                                                                                                                                                                                                                             , line 174, in _create_c10d_store
    return TCPStore(
torch.distributed.DistNetworkError: The client socket has timed out after 600s w                                                                                                                                                                                                                                             hile trying to connect to (10.60.2.1, 53591).

**Comment by starage2020** [comment]
用的是V100的卡 32G显存。

**Comment by zhipuch** [comment]
看报错消息，是连接超时之类的问题吧，检查路径问题？

**Comment by starage2020** [comment]
> 看报错消息，是连接超时之类的问题吧，检查路径问题？

谢谢，已解决，是容器IP配置的问题。
