### ISSUE TITLE
GLM-4-9B-chat，运行报错： CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmStridedBatchedExFix

### ISSUE THREAD

**Issue by sly123197811** [THUDM/GLM-4#68]
### System Info / 系統信息

cuda:12
pytorch: 2.1.2
python:3.10.0

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

现象：
1. 当输入的文本<=18个字符时，一切正常。如：
![image](https://github.com/THUDM/GLM-4/assets/30062210/3cf94bf3-ab7a-40bc-8caf-701a7eaf8704)
2. 当输入文本超过18个字符时，如：“请参考以上文本，生成一段200字的内容，语气要严谨”，报如下错误：
![image](https://github.com/THUDM/GLM-4/assets/30062210/120e9447-6623-4dac-bc08-a8b7ca7eddec)
核心代码如下:
![image](https://github.com/THUDM/GLM-4/assets/30062210/31269bc4-22bd-4028-8e21-c76165429363)

### Expected behavior / 期待表现

如果是环境问题，为什么输入尺寸足够小时，可以正常执行
同时，其它模型也可正常运行，torch+cuda环境应该是没问题

**Comment by zRzRzRzRzRzRzR** [comment]
你的输入超过了你设定的模型输入限制吧，你设置了多少的输入限制

**Comment by sly123197811** [comment]
> 你的输入超过了你设定的模型输入限制吧，你设置了多少的输入限制

问题我刚刚解决了，是因为我的显卡比较老，不支持bfloat16导致的，设置为torch.float16 后不再报错。我的输入设置的32767
但是，至于为什么当输入足够短时，bfloat16可以计算，不理解原因，不知道有没有大佬了解此问题的本质，求指教

**Comment by shams2023** [comment]
File "C:\Users\hello\.cache\huggingface\modules\transformers_modules\glm4\modeling_chatglm.py", line 260, in forward     value_layer = value_layer.view(output_size[0] * output_size[1], value_layer.size(2), -1) RuntimeError: shape '[224, 7, -1]' is invalid for input of size 28672
如何解决，大佬们

**Comment by zRzRzRzRzRzRzR** [comment]
没有遇到这个问题，确定你的文件是huggingface上最新的
